.PHONY: init-env

init-env: ## Interactive setup for .env file (essential secrets only)
	@if [ -f .env ]; then \
		read -p "⚠️  .env file already exists. Overwrite? (y/N) " confirm; \
		if [ "$$confirm" != "y" ] && [ "$$confirm" != "Y" ]; then \
			echo "Operation cancelled."; \
			exit 0; \
		fi; \
	fi; \
	echo "📝 Setting up essential environment variables..."; \
	\
	# 1. Atlassian Secrets (Personal) \
	read -p "Atlassian Domain [https://diamondhead.atlassian.net]: " atlassian_domain; \
	atlassian_domain=$${atlassian_domain:-https://diamondhead.atlassian.net}; \
	read -p "Atlassian Email [ohi@diamondhead.tech]: " atlassian_email; \
	atlassian_email=$${atlassian_email:-ohi@diamondhead.tech}; \
	read -p "Atlassian API Token (Jira/Confluence): " atlassian_token; \
	\
	# 2. GitHub Secrets (Personal) \
	read -p "GitHub Token (GH_TOKEN): " github_token; \
	\
	# 3. Internal / Auto-derived variables \
	repo_root=$$(pwd); \
	mcp_auth="d42bc6ec9a28fd4dfcf96d673f5ca40e"; \
	\
	# Write to .env \
	echo "# Generated by make init-env on $$(date)" > .env; \
	echo "# --- User Secrets (Manually configured) ---" >> .env; \
	echo "ATLASSIAN_DOMAIN=$$atlassian_domain" >> .env; \
	echo "ATLASSIAN_EMAIL=$$atlassian_email" >> .env; \
	echo "ATLASSIAN_JIRA_URL=$$atlassian_domain" >> .env; \
	echo "ATLASSIAN_JIRA_USERNAME=$$atlassian_email" >> .env; \
	echo "ATLASSIAN_JIRA_API_TOKEN=$$atlassian_token" >> .env; \
	echo "ATLASSIAN_CONFLUENCE_URL=$$atlassian_domain" >> .env; \
	echo "ATLASSIAN_CONFLUENCE_USERNAME=$$atlassian_email" >> .env; \
	echo "ATLASSIAN_CONFLUENCE_API_TOKEN=$$atlassian_token" >> .env; \
	echo "GH_TOKEN=$$github_token" >> .env; \
	echo "GITHUB_TOKEN=$$github_token" >> .env; \
	echo "" >> .env; \
	echo "# --- Project Internals (Auto-derived or defaults) ---" >> .env; \
	echo "DOTFILES_AI_REPO_ROOT=$$repo_root" >> .env; \
	echo "MCP_AUTH_TOKEN=$$mcp_auth" >> .env; \
	echo "MCP_GATEWAY_AUTH_TOKEN=$$mcp_auth" >> .env; \
	echo "MCP_GATEWAY_TOKEN=$$mcp_auth" >> .env; \
	echo "# NEXUS_PATH=~/program/nexus" >> .env; \
	\
	echo "✅ .env file has been created with essential secrets."
