.PHONY: init-env setup-apm-env

setup-apm-env: ## .env ファイルの雛形作成（初回のみ）
	@if [ ! -f .env ]; then \
		cp .env.example .env && \
		echo "✓ Created .env from .env.example"; \
	else \
		echo "✓ .env already exists"; \
	fi

init-env: ## Interactive setup for .env file (essential secrets only)
	@if [ -f .env ]; then \
		read -p "⚠️  .env file already exists. Overwrite? (y/N) " confirm; \
		if [ "$$confirm" != "y" ] && [ "$$confirm" != "Y" ]; then \
			echo "Operation cancelled."; \
			exit 0; \
		fi; \
	fi; \
	echo "📝 Setting up essential environment variables..."; \
	\
	# 1. AI Agent API Keys \
	read -p "Anthropic API Key: " anthropic_key; \
	read -p "OpenAI API Key: " openai_key; \
	read -p "Gemini API Key: " gemini_key; \
	read -p "Cursor API Key: " cursor_key; \
	\
	# 2. Atlassian Secrets (Personal) \
	read -p "Atlassian Domain [https://diamondhead.atlassian.net]: " atlassian_domain; \
	atlassian_domain=$${atlassian_domain:-https://diamondhead.atlassian.net}; \
	read -p "Atlassian Email [ohi@diamondhead.tech]: " atlassian_email; \
	atlassian_email=$${atlassian_email:-ohi@diamondhead.tech}; \
	read -p "Atlassian API Token (Jira/Confluence): " atlassian_token; \
	\
	# 3. GitHub Secrets (Personal) \
	read -p "GitHub Token (GH_TOKEN): " github_token; \
	\
	# 4. Path Settings \
	read -p "Nexus Path [~/program/nexus]: " nexus_path; \
	nexus_path=$${nexus_path:-$${HOME}/program/nexus}; \
	nexus_path=$$(echo "$$nexus_path" | sed "s|^~\(/\|$$\)|$$HOME\1|"); \
	\
	# Chronos-Graph Path detection \
	if [ -d "$${HOME}/program/private/chronos-graph" ]; then \
	        cg_default="$${HOME}/program/private/chronos-graph"; \
	else \
	        cg_default="$${HOME}/program/chronos-graph"; \
	fi; \
	read -p "Chronos-Graph Path [$$cg_default]: " chronos_graph_path; \
	chronos_graph_path=$${chronos_graph_path:-$$cg_default}; \
	chronos_graph_path=$$(echo "$$chronos_graph_path" | sed "s|^~\(/\|$$\)|$$HOME\1|"); \
	\
	# 5. Internal / Auto-derived variables \
	# MCP_AUTH can be used to supply a stable secret for CI/production. \
	# For local development, a random token is generated if MCP_AUTH is unset. \
	repo_root=$$(pwd); \
	mcp_auth=$${MCP_AUTH:-$$(openssl rand -hex 16 2>/dev/null || echo "d42bc6ec9a28fd4dfcf96d673f5ca40e")}; \
	\
	# Write to .env \
	echo "# Generated by make init-env on $$(date)" > .env; \
	echo "# --- AI Agent API Keys ---" >> .env; \
	printf "ANTHROPIC_API_KEY=%s\n" "$$anthropic_key" >> .env; \
	printf "OPENAI_API_KEY=%s\n" "$$openai_key" >> .env; \
	printf "GEMINI_API_KEY=%s\n" "$$gemini_key" >> .env; \
	printf "CURSOR_API_KEY=%s\n" "$$cursor_key" >> .env; \
	echo "" >> .env; \
	echo "# --- Agent Management & Isolation ---" >> .env; \
	printf "CLAUDE_CONFIG_DIR=%s/.claude\n" "$$repo_root" >> .env; \
	echo "GEMINI_SANDBOX=true" >> .env; \
	echo "" >> .env; \
	echo "# --- Atlassian Secrets (Personal) ---" >> .env; \
	printf "ATLASSIAN_DOMAIN=%s\n" "$$atlassian_domain" >> .env; \
	printf "ATLASSIAN_EMAIL=%s\n" "$$atlassian_email" >> .env; \
	printf "ATLASSIAN_JIRA_URL=%s\n" "$$atlassian_domain" >> .env; \
	printf "ATLASSIAN_JIRA_USERNAME=%s\n" "$$atlassian_email" >> .env; \
	printf "ATLASSIAN_JIRA_API_TOKEN=%s\n" "$$atlassian_token" >> .env; \
	printf "ATLASSIAN_CONFLUENCE_URL=%s\n" "$$atlassian_domain" >> .env; \
	printf "ATLASSIAN_CONFLUENCE_USERNAME=%s\n" "$$atlassian_email" >> .env; \
	printf "ATLASSIAN_CONFLUENCE_API_TOKEN=%s\n" "$$atlassian_token" >> .env; \
	printf "GH_TOKEN=%s\n" "$$github_token" >> .env; \
	printf "GITHUB_TOKEN=%s\n" "$$github_token" >> .env; \
	printf "GITHUB_PERSONAL_ACCESS_TOKEN=%s\n" "$$github_token" >> .env; \
	echo "" >> .env; \
	echo "# --- Path Settings ---" >> .env; \
	printf "NEXUS_PATH=%q\n" "$$nexus_path" >> .env; \
	printf "CHRONOS_GRAPH_PATH=%q\n" "$$chronos_graph_path" >> .env; \
	echo "" >> .env; \
	echo "# --- Project Internals (Auto-derived or defaults) ---" >> .env; \
	printf "DOTFILES_AI_REPO_ROOT=%q\n" "$$repo_root" >> .env; \
	printf "MCP_AUTH_TOKEN=%s\n" "$$mcp_auth" >> .env; \
	echo "MCP_GATEWAY_AUTH_TOKEN=$$mcp_auth" >> .env; \
	echo "MCP_GATEWAY_TOKEN=$$mcp_auth" >> .env; \
	chmod 600 .env; \
	\
	echo "✅ .env file has been created with essential secrets."

.PHONY: install-ollama
install-ollama: ## Install Ollama using official script
	@echo "🦙 Installing Ollama..."
	@tmpfile=$$(mktemp); \
	curl -fsSL https://ollama.com/install.sh -o "$$tmpfile"; \
	sh "$$tmpfile"; \
	rm -f "$$tmpfile"
