mcpServers:
  SQLite:
    enabled: true
  filesystem:
    enabled: true
    args:
      - /home/y_ohi/dotfiles/components/dotfiles-ai
    volumes:
      - /home/y_ohi/dotfiles/components/dotfiles-ai:/home/y_ohi/dotfiles/components/dotfiles-ai
  sequentialthinking:
    enabled: true
  skillport:
    enabled: true
