mcpServers:
  SQLite:
    enabled: true
  filesystem:
    enabled: true
    args:
      - /home/y_ohi/dotfiles/components/dotfiles-ai
      - /home/y_ohi
  playwright:
    enabled: true
  tavily:
    enabled: true
  sequentialthinking:
    enabled: true
  magic:
    enabled: true
  morphllm-fast-apply:
    enabled: true
  serena:
    enabled: true
  chrome-devtools:
    enabled: true
  github-official:
    enabled: true
  docker:
    enabled: true
  dockerhub:
    enabled: true
  skillport:
    enabled: true
