#!/usr/bin/env bash
# _scripts/test-sync-agents.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "Running Sync Agents Verification Tests..."

CATALOG="$REPO_ROOT/agent-skills/AVAILABLE_SKILLS.md"
GLOBAL_RULES="$REPO_ROOT/global-rules/AGENTS.global.md"
CATALOG_BAK="$CATALOG.bak"
GLOBAL_RULES_BAK="$GLOBAL_RULES.bak"

cp "$CATALOG" "$CATALOG_BAK"
cp "$GLOBAL_RULES" "$GLOBAL_RULES_BAK"

cleanup() {
    mv "$CATALOG_BAK" "$CATALOG" || true
    mv "$GLOBAL_RULES_BAK" "$GLOBAL_RULES" || true
}
trap cleanup EXIT

# Clear the generated catalog block to verify that sync_agents.sh restores it.
sed -i.tmp '/<available_skills>/,/<[/]available_skills>/d' "$CATALOG"
rm -f "$CATALOG.tmp"

# The global prompt is intentionally not generated by SkillPort. Record its
# checksum so the test can assert that sync-agents leaves it untouched.
global_before=$(sha256sum "$GLOBAL_RULES" | awk '{print $1}')

bash "$REPO_ROOT/_scripts/sync_agents.sh" >/dev/null

if ! grep -qF "<!-- SKILLPORT_START -->" "$CATALOG"; then
    echo "FAIL: <!-- SKILLPORT_START --> marker not found in agent-skills/AVAILABLE_SKILLS.md"
    exit 1
fi
if ! grep -qF "<!-- SKILLPORT_END -->" "$CATALOG"; then
    echo "FAIL: <!-- SKILLPORT_END --> marker not found in agent-skills/AVAILABLE_SKILLS.md"
    exit 1
fi
if ! grep -qF "<available_skills>" "$CATALOG"; then
    echo "FAIL: <available_skills> not found in agent-skills/AVAILABLE_SKILLS.md"
    exit 1
fi
if ! awk '/<available_skills>/, /<\/available_skills>/ { if ($0 ~ /<skill>/) { found=1; exit } } END { if (!found) exit 1 }' "$CATALOG"; then
    echo "FAIL: <available_skills> section is empty or missing <skill> elements"
    exit 1
fi
if ! grep -qF "External skills (anthropics/*, superpowers/*)" "$CATALOG"; then
    echo "FAIL: External skills note not found in agent-skills/AVAILABLE_SKILLS.md"
    exit 1
fi
if ! grep -qF "<name>pdf</name>" "$CATALOG"; then
    echo "FAIL: pdf skill entry not found in agent-skills/AVAILABLE_SKILLS.md"
    exit 1
fi

global_after=$(sha256sum "$GLOBAL_RULES" | awk '{print $1}')
if [[ "$global_before" != "$global_after" ]]; then
    echo "FAIL: sync_agents.sh modified global-rules/AGENTS.global.md"
    exit 1
fi
if grep -qF "<available_skills>" "$GLOBAL_RULES"; then
    echo "FAIL: global-rules/AGENTS.global.md must not embed the full skill catalog"
    exit 1
fi
if ! grep -qF "agent-skills/AVAILABLE_SKILLS.md" "$GLOBAL_RULES"; then
    echo "FAIL: global-rules/AGENTS.global.md must reference the on-demand skill catalog"
    exit 1
fi

echo "PASS: agent-skills/AVAILABLE_SKILLS.md verified."
echo "PASS: global-rules/AGENTS.global.md remains lightweight and unchanged."
echo "🎉 All sync agents tests passed successfully!"
